### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#2]
Set up Python CI/CD, with test, linting, etc.

**Comment by jnik-aarhus** [comment]
@clausjuhl [https://travis-ci.com/plans](Travis-ci) is the most commonly used CI/CD and recommended by leading Python developers. The first 100 builds are free, and after that we'd have to pay. I think we can get by on the Bootstrap plan, approx. DKK 5200/year.

**Comment by clausjuhl** [comment]
@jnik-aarhus That's fine with me, but is it better than Circle CI (much cheaper)?: https://circleci.com/pricing/usage/

**Comment by jnik-aarhus** [comment]
For our needs, Travis and Circle should be equally well suited. It looks like those pricing plans are not ready yet? However you are right, they are still cheaper, https://circleci.com/pricing/ shows 50$/month with unlimited build minutes and two containers, approx DKK 4100/year. And we could move to the new plan when it's ready?
