### ISSUE TITLE
Decide on style for code + documentation

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#5]
Probably PEP8, perhaps Google's style guide?

**Comment by clausjuhl** [comment]
I suggest we use black: https://github.com/psf/black

**Comment by jnik-aarhus** [comment]
Decision: We use [black](https://github.com/psf/black) and [flake8](https://github.com/PyCQA/flake8). These are added to CI/CD, refer to [`.circleci/config.yml`](https://github.com/aarhusstadsarkiv/digital-archive/blob/master/.circleci/config.yml). Note that black needs to have the setting 
```
[tool.black]
line-length = 79
```
in [`pyproject.toml`](https://github.com/aarhusstadsarkiv/digital-archive/blob/master/pyproject.toml) to avoid conflicts with flake8.
