### ISSUE TITLE
Consider new branching practices

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#54]
Having PRs to master is getting a bit messy. I'd like to have master be a stable branch with version tags. 
Suggestion: Something like this:
![image](https://user-images.githubusercontent.com/56030935/67397394-6ee09180-f5a9-11e9-8159-4ced09903d26.png)
Perhaps except for hotfix and release branches.

**Comment by clausjuhl** [comment]
Self-evident!

**Comment by jnik-aarhus** [comment]
This (hopefully more simple) diagram shows my idea.
![branch_diagram](https://user-images.githubusercontent.com/56030935/67479080-8f6a2380-f65d-11e9-96fa-3d30d17e0920.png)

**Comment by jnik-aarhus** [comment]
We now have a master and development branch, both protected. 
See https://github.com/aarhusstadsarkiv/digital-archive/branches for an overview.
