### ISSUE TITLE
Generate stats over received file types

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#6]
We need an overview of the type of files received, in order to 

- Create a blacklist for trash files
- Ascertain how many unidentified files we receive on average
- Prioritise implementation based on most common file types

**Comment by clausjuhl** [comment]
Could we use a simple csv-file (extension, description) as blacklist? I'll mail you an axample.

**Comment by jnik-aarhus** [comment]
Great idea - those are easy to parse.

**Comment by jnik-aarhus** [comment]
Closed with #23
